name: Build releases

on:
  release:
    types: [released]
  
permissions:
  id-token: write
  contents: write

jobs:
  call-build-release:
    uses: prefapp/firestarter-workflows/.github/workflows/build_images.yaml@v1
    secrets: inherit
    with:
      type: releases
      from: ${{ github.event.release.tag_name }}
      auth_strategy: azure_oidc

