name: Build snapshots

on:
  release:
    types: [prereleased]
  
  pull_request:
    types: [labeled, synchronize]
    branches:
      - 
  push:
    branches:
      - 
  
permissions:
  id-token: write
  contents: write

jobs:
  call-build-push:
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'autodeploy') }}
    uses: prefapp/firestarter-workflows/.github/workflows/build_images.yaml@v1
    secrets: inherit
    with:
      type: snapshots
      from: ${{ github.sha }}
      auth_strategy: azure_oidc

  call-build-prerelease:
    if: ${{ github.event_name == 'release' && github.event.release.prerelease == true }}
    uses: prefapp/firestarter-workflows/.github/workflows/build_images.yaml@v1
    secrets: inherit
    with:
      type: snapshots
      from: ${{ github.event.release.tag_name }}
      auth_strategy: azure_oidc

